# remote_theme: pages-themes/minimal@v0.2.0
theme: minima
plugins:
 - jekyll-remote-theme
 - jekyll-redirect-from
 - jekyll-sitemap
title: Centennial Software Solutions® LLC
description: ASAP Edge AI, Embedded Systems and FPGA Support.
email: help@centennialsoft.com
url: "https://www.centennialsoftwaresolutions.com"
show_downloads: false
baseurl: ""
header_pages:
  - about/index.md
  - help/index.md
  - contact.md
author:
  name: Centennial Software Solutions® LLC
  email: help@centennialsoft.com
