remote_theme: pages-themes/minimal@v0.2.0
plugins:
 - jekyll-remote-theme
 - jekyll-redirect-from
title: Centennial Software Solutions LLC Home Page
description: The Centennial Software Solutions LLC home page.
show_downloads: false
baseurl: ""
exclude:
  - post/*
