# remote_theme: pages-themes/minimal@v0.2.0
theme: minima
plugins:
 - jekyll-remote-theme
 - jekyll-redirect-from
 - jekyll-sitemap
title: Centennial Software Solutions
description: Expert PetaLinux Tools Support
email: help@centennialsoft.com
show_downloads: false
baseurl: ""
header_pages:
  - about/index.md
  - help/index.md
  - contact.md
